<a href="https://colab.research.google.com/github/efacundoargana/jardines_geo_coding/blob/main/jardines_geo_coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install googlemaps

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting googlemaps
  Downloading googlemaps-4.6.0.tar.gz (31 kB)
Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.7/dist-packages (from googlemaps) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2022.9.24)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.10)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py) ... done
  Created wheel for googlemaps: filename=googlemaps-4.6.0-py3-none-any.whl size=38554 sha256=2b79ff3f48565fb26bd696fab19839fc83f5814f5b84a5f50051cf6af03cdebb
  Stored in directory: /root/.cache/pip/wheels/80/db/c0/6d958585fa97b20e250bf437acf7e6e715b4809c2dd4e55367
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.6.0

In [ ]:
# libraries
import googlemaps
from datetime import datetime
import pandas as pd

In [ ]:
# API key
KEY = ""
gmaps = googlemaps.Client(key=KEY)

In [ ]:
COORDINATES = (-34.597058,-58.436354)

reverse_geocode_result = gmaps.reverse_geocode(COORDINATES)

Formated_Address = []
Latitude = []
Longitude = []
Place_ID = []
Types_ = []

for i in range(0, len(reverse_geocode_result)):
  Formated_Address.append(reverse_geocode_result[i]["formatted_address"])
  Latitude.append(reverse_geocode_result[i]["geometry"]["location"]["lat"])
  Longitude.append(reverse_geocode_result[i]["geometry"]["location"]["lng"])
  Place_ID.append(reverse_geocode_result[i]['place_id'])
  Types_.append(reverse_geocode_result[i]['types'])

results_Geo = pd.DataFrame(data={'Formated_Address': Formated_Address,
                                'Latitude': Latitude,
                                'Longitude': Longitude,
                                'Place_ID': Place_ID,
                                'Types_': Types_})

ApiError: ignored

In [ ]:
results_Geo.head()

                                  Formated_Address  ...                                         Types_
0  Aguirre 596, C1414 ASL, Buenos Aires, Argentina  ...                               [street_address]
1                  CH37+5F Buenos Aires, Argentina  ...                                    [plus_code]
2        Aguirre 600-500, C1414ASL CABA, Argentina  ...                                        [route]
3            Villa Crespo, Buenos Aires, Argentina  ...  [political, sublocality, sublocality_level_1]
4                       Comuna 15, CABA, Argentina  ...       [administrative_area_level_2, political]

[5 rows x 5 columns]

In [ ]:
places_nearby_example = gmaps.places_nearby(location = (COORDINATES), radius = 1000, type=['primary_school'])
res = len(places_nearby_example['results'])
results = places_nearby_example['results']
lat_ = []
lng_ = []
name_ = []
place_id_ = []
types_ = []
vicinity_ = []
for rr_ in range(0,res):
    lat = results[rr_]['geometry']['location']['lat']
    lng = results[rr_]['geometry']['location']['lng']
    name = results[rr_]['name']
    place_id = results[rr_]['place_id']
    types = results[rr_]['types']
    vicinity = results[rr_]['vicinity']
    lat_.append(lat)
    lng_.append(lng)
    name_.append(name)
    place_id_.append(place_id)
    types_.append(types)
    vicinity_.append(vicinity)
results = pd.DataFrame(data={'lat':lat_,
                                'lng':lng_,
                                'name':name_,
                                'place_id':place_id_,
                                'types':types_,
                                'vicinity':vicinity_})

In [ ]:
results.shape

(16, 6)

In [ ]:
results

          lat  ...                              vicinity
0  -34.594628  ...                           Malabia 964
1  -34.596125  ...              Julián Álvarez 1030, DRV
2  -34.592038  ...           Armenia 1353, C1414DKC, DKC
3  -34.590528  ...                          Serrano 1320
4  -34.598828  ...                      Acevedo 357, DJG
5  -34.590537  ...                     Uriarte 1152, DAH
6  -34.595535  ...              C1414DHO, Gurruchaga 739
7  -34.601028  ...                        Aráoz 234, DPF
8  -34.598638  ...                      Camargo 725, AHO
9  -34.601738  ...              240, DRF, Julián Álvarez
10 -34.591141  ...  C1414DEY, Serrano 1261, Buenos Aires
11 -34.592038  ...                          Armenia 1353
12 -34.603956  ...            Avenida Angel Gallardo 246
13 -34.603007  ...                      Lambaré 975, ABC
14 -34.598485  ...                    Pringles 1165, AEU
15 -34.592245  ...                          Humboldt 742

[16 rows x 6 columns]